project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

website:
  title: "sokmean.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - map.qmd
      - motivation.qmd

# supplying a light ("minty") and dark ("slate") theme to toggle between
format:
  html:
    theme: 
      light: lumen
      dark: solar
    css: styles.css

