project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

website:
  title: "sokmean.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - map.qmd

format:
  html:
    theme:
      light: minty
      dark: solar

editor: visual

